config/routes.rb
AdJudge::Application.routes.draw do
  root to: 'posts#index'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'
  get '/auth/:provider/callback', to:'sessions#signin'
  get '/auth/failure', to: redirect('/')

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
    member do
      post 'fake_vote'
    end
    resources :comments, only: [:create]
  end

  resources :users, only: [:show, :create, :edit, :update]
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable

  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false
  validates :user_name, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 5}

  sluggable_column :user_name

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.user_name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.password = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.email = auth.info.email
      user.image_url = auth.info.image
      user.save!
    end
  end

  def admin?
    self.role == "admin"
  end

  def moderator?
    self.role == "moderator"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new  
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You are registered."
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post_vote_true = Kaminari.paginate_array(Post.where(id: @user.votes.where(vote: true).pluck(:voteable_id).uniq).order(:up_votes).reverse).page(params[:page]).per(6)
    @post_vote_false = Kaminari.paginate_array(Post.where(id: @user.votes.where(vote: false).pluck(:voteable_id).uniq).order(:down_votes).reverse).page(params[:page]).per(6)

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end

  def set_user
    @user = User.find_by slug: params[:id]
  end

  def require_same_user
    if current_user != @user
      flash[:error] = "You're not allow to do that."
      redirect_to root_path
    end
  end
end

app/views/users/_post.html.erb
<!-- This partial is only for user's info page -->
<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 post">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 center">
    <h4 class="lead one-line-title"><%= link_to post.title, post_path(post) %></h4>
  </div>
  <iframe width="320" height="180" src="//www.youtube.com/embed/<%= post.youtube_video_id %>" frameborder="0" allowfullscreen></iframe>
  <br>
  <div id="action_column_left_<%=post.id%>" class="col-xs-4 col-sm-3 col-sm-offset-2 col-md-3 col-md-offset-2 col-lg-3 col-lg-offset-2 action_column_left">
    <%= render 'shared/social_share_column', post: post %>
  </div>
  <div id="action_column_right_<%=post.id%>" class="col-xs-8 col-sm-7 col-md-7 col-lg-7  action_column_right">
    <%= render 'progress_bar', post: post %>
  </div>
</div>

app/views/users/_progress_bar.html.erb
<% if params[:tab] == 'ups' %>
  <p class="vote_result_text">
    你和<%= raw number_to_percentage(post.up_ratio, precision: 0) %>的人喜歡這支廣告
  </p>
<% elsif params[:tab] == 'downs' %>
  <p class="vote_result_text">
    你和<%= raw number_to_percentage(post.down_ratio, precision: 0) %>的人討厭這支廣告
  </p>
<% end %>
<br>
<div class="progress col-xs-12 col-sm-8 col-md-9 col-lg-7">
  <div class="progress-bar progress-bar-success" style= "width: <%== number_to_percentage(post.up_ratio, precision: 2) %>;"></div>
  <div class="progress-bar progress-bar-warning" style= "width: <%== number_to_percentage(post.down_ratio, precision: 2) %>;" ></div>
</div>

app/views/users/new.html.erb
<div class='col-xs-10 col-sm-6 col-md-4 col-lg-4 center'>
  <%= render 'shared/content_title', title: '註冊' %>
  <%= form_for @user do |f| %>
    <%= render 'shared/errors', obj: @user %>
    <div class='form-group'>
      <%= f.label :user_name %>
      <%= f.text_field :user_name %>
    </div>
    <div class='form-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <%= f.submit '註冊', class: "btn btn-success black" %>
  <% end %>
</div>

app/views/users/show.html.erb
<ul id="user_tab" class='nav nav-tabs'>
  <li class='<%= 'active' if params[:tab] == 'ups' %>user_tab'>
    <%= link_to "喜歡 (#{@user.votes.where(vote: true).size})", user_path(@user, tab: 'ups') %>
  </li>
  <li class='<%= 'active' if params[:tab] == 'downs' %>user_tab'>
    <%= link_to "討厭(#{@user.votes.where(vote: false).size})", user_path(@user, tab: 'downs') %>
  </li>
</ul>

<% if params[:tab] == 'ups' %>
  <div id="main_items" class="center2">
    <% @post_vote_true.each do |post| %>
      <%= render 'post', post: post, tab: 'ups' %>
    <% end %>
  </div>
  <div class="paginate">
    <%= paginate @post_vote_true, remote: true %>
  </div>
<% elsif params[:tab] == 'downs' %>
  <div id="main_items" class="center2">
    <% @post_vote_false.each do |post| %>
      <%= render 'post', post: post %>
    <% end %>
  </div>
  <div class="paginate">
    <%= paginate @post_vote_false, remote: true %>
  </div>
<% end %>

app/views/users/show.js.erb
<% if params[:tab] == 'ups' %>
  $("#main_items").append($("<%= j(render @post_vote_true) %>"));
  $(".pagination").html("<%= j(paginate @post_vote_true, :remote => true) %>");
<% elsif params[:tab] == 'downs' %>
  $("#main_items").append($("<%= j(render @post_vote_false) %>"));
  $(".pagination").html("<%= j(paginate @post_vote_false, :remote => true) %>");
<% end %>