config/routes.rb
AdJudge::Application.routes.draw do
  root to: 'posts#index'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'
  get '/auth/:provider/callback', to:'sessions#signin'
  get '/auth/failure', to: redirect('/')

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
    member do
      post 'fake_vote'
    end
    resources :comments, only: [:create]
  end

  resources :users, only: [:show, :create, :edit, :update]
end

app/views/shared/_content_title.html.erb
<p class='lead center'>
  <%= title %>
  <br/>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row center'>
    <div class='alert alert-danger col-xs-10 col-sm-10 col-md-10 col-lg-10 center'>
      <h5>Please fix following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_fake_vote.html.erb
<div class='center vote_buttons_placement'>
  <%= link_to fake_vote_post_path(post), method: 'post', remote: true, class: 'btn btn-lg btn-success' do %>
    <span class='glyphicon glyphicon-thumbs-up black'></span>
  <% end %>
  <%= link_to fake_vote_post_path(post), method: 'post', remote: true, class: 'btn btn-lg btn-danger' do %>
    <span class='glyphicon glyphicon-thumbs-down black'></span>
  <% end %>
</div>

app/views/shared/_livehousein.html.erb
<div class="center">
<iframe width="960" height="310" src="https://livehouse.in/embed/channel/112424" frameborder="0" allowfullscreen></iframe>
</div>

app/views/shared/_progress_bar.html.erb
<% if logged_in? %>
  <% if params[:vote] == "true" %>
    <p class="vote_result_text">
      你和<%= raw number_to_percentage(post.up_ratio, precision: 0) %>的人喜歡這支廣告
    </p>
  <% elsif params[:vote] == "false" %>
    <p class="vote_result_text">
      你和<%= raw number_to_percentage(post.down_ratio, precision: 0) %>的人討厭這支廣告
    </p>
  <% elsif vote.vote %>
    <p class="vote_result_text">
      你和<%= raw number_to_percentage(post.up_ratio, precision: 0) %>的人喜歡這支廣告
    </p>
  <% else%>
    <p class="vote_result_text">
      你和<%= raw number_to_percentage(post.down_ratio, precision: 0) %>的人討厭這支廣告
    </p>
  <% end %>
  <br>
  <div class="progress col-xs-12 col-sm-8 col-md-9 col-lg-7">
    <div class="progress-bar progress-bar-success" style= "width: <%== number_to_percentage(post.up_ratio, precision: 2) %>;"></div>
    <div class="progress-bar progress-bar-warning" style= "width: <%== number_to_percentage(post.down_ratio, precision: 2) %>;" ></div>
  </div>

<% else %>
  <p class="vote_result_text">
    登入，讓你的投票算數
  </p>
  <br>
  <% if post.up_ratio >= post.down_ratio %>
    <div class="progress col-xs-12 col-sm-8 col-md-9 col-lg-7">
      <div class="progress-bar progress-bar-success" style= "width: <%== number_to_percentage(post.up_ratio, precision: 2) %>;"></div>
      <div class="progress-bar progress-bar-warning" style= "width: <%== number_to_percentage(post.down_ratio, precision: 2) %>;" ></div>
    </div>
  <% elsif post.up_ratio < post.down_ratio %>
    <div class="progress col-xs-12 col-sm-8 col-md-9 col-lg-7">
      <div class="progress-bar progress-bar-success" style= "width: <%== number_to_percentage(post.up_ratio, precision: 2) %>;"></div>
      <div class="progress-bar progress-bar-warning" style= "width: <%== number_to_percentage(post.down_ratio, precision: 2) %>;" ></div>
    </div>
  <% else %>
    <p class="vote_result_text">
      還沒有人投票
    </p>
  <% end %>
  <br>
  
<% end %>

app/views/shared/_social_share_column.html.erb
<div id="fb_share_<%=post.id%>" class="social_share_column" post-id="<%=post.slug%>" >
  <%= image_tag("facebook_share.png", alt: "share", size: "120x46") %>


</div>
<!-- 
  <div class="social_share_column" post-id="<%=post.slug%>">
    <%= link_to image_tag("facebook_share.png", alt: "login", size: "108x40"), login_path %>
  </div>
-->

app/views/shared/_vote_buttons.html.erb
<div class='center vote_buttons_placement'>
  <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true, class: 'btn btn-lg btn-success' do %>
    <span class='glyphicon glyphicon-thumbs-up black'></span>
  <% end %>
  <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true, class: 'btn btn-lg btn-danger'  do %>
    <span class='glyphicon glyphicon-thumbs-down black'></span>
  <% end %>
</div>