config/routes.rb
AdJudge::Application.routes.draw do
  root to: 'posts#index'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'
  get '/auth/:provider/callback', to:'sessions#signin'
  get '/auth/failure', to: redirect('/')

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
    member do
      post 'fake_vote'
    end
    resources :comments, only: [:create]
  end

  resources :users, only: [:show, :create, :edit, :update]
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle navbar-xs" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="logo-xs">
      <%= link_to image_tag("adjudge_logo.png", alt: "Ad Judge", size: "113x26"), root_path%>
    </span>
    <span class="glyphicon glyphicon-align-justify toggle-xs"></span>
  </button>

</div>
<div class="collapse navbar-collapse">
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <%= link_to('',  class: 'dropdown-toggle', 'data-toggle' => 'dropdown') do %>
        <span class='glyphicon glyphicon-align-justify'></span>
      <% end %>
        <ul class='dropdown-menu dropdown-menu-left'>
          <li>
            <%= link_to root_path(order: 'up_votes') do %>
              最多人喜歡的廣告
            <% end %>
          </li>
          <li>
            <%= link_to root_path(order: 'down_votes') do %>
              最多人討厭的廣告
            <% end %>
          </li>        
          <li>
            <%= link_to root_path(order: 'the_latest') do %>
              最新的廣告
            <% end %>
          </li>
        </ul>
    </li>
    <li class="logo hidden-xs">
      <%= link_to image_tag("adjudge_logo.png", alt: "Ad Judge", size: "113x26"), root_path%>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
  <% if logged_in? %>
    <li class="dropdown">
      <%= link_to('',  class: 'dropdown-toggle', 'data-toggle' => 'dropdown') do %>
        <%= current_user.user_name %>
        
      <% end %>
      <ul class='dropdown-menu dropdown-menu-right'>
        <li>
          <%= link_to user_path(current_user) do %>
            <span class='glyphicon glyphicon-user'></span>
            我的裁決
          <% end %>
        </li>
        <li>
          <%= link_to logout_path do %>
            <span class='glyphicon glyphicon-circle-arrow-left'></span>
            登出
          <% end %>
        </li>
        <% if current_user.admin? %>
          <li>
            <%= link_to new_post_path do %>
              <span class='glyphicon glyphicon-cloud-upload'></span>
              上傳廣告
            <% end %>
          </li> 
        <% end %>
      </ul>
    </li>
  <% else %>
    <li>
      <%= link_to "登入", login_path %>
    </li>
  <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimal-ui">
    <title>廣告裁判</title>
    <meta name="description" content="Ads worth spreading">
    <meta name="author" content="">
    <%= yield :specific_og_metas %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <script src="http://cdn.embed.ly/jquery.embedly-3.0.5.min.js" type="text/javascript"></script>
    <script src="http://cdn.embed.ly/jquery.preview-0.3.2.min.js" type="text/javascript"></script> 
    <link rel="stylesheet" href="http://cdn.embed.ly/jquery.preview-0.3.2.css" />
    <%= favicon_link_tag %>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39751836-3', 'ad-judge.com');
  ga('send', 'pageview');

</script>
  </head>
  <body>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '<%= Settings.facebook.key %>',
          xfbml      : true,
          version    : 'v2.0'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/zh_TW/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
    <header>
      <nav class="navbar navbar-fixed-top navbar-inverse center" role="navigation">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
        
    <div id="main" role="main">
      <div class="container center container_decoration">
         <div class="row center">
          <div class="col-sm-12 col-mid-12 col-lg-12 center row_decoration">
            <%= render 'layouts/messages' %>
            <%= render 'shared/livehousein' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
  
</html>